### ISSUE TITLE
Tab completion problem

### ISSUE THREAD

**Issue by Piasy** [shockone/black-screen#460]
1. It's case sensitive now, could it be case insensitive?
2. Executing local binary could not tab complete. e.g. when I type `./gr`, it could not tab complete to `./gradlew`, any other command start with a path could not be tab complete too.
3. Command after pipe (`|`) could not tab complete. e.g. `ls . | gr` could not tab complete to `ls . | grep`.

**Comment by shockone** [comment]
Case sensitivity is fixed now.

**Comment by shockone** [comment]
Relative paths are fixed in 0.1.2.

**Comment by shockone** [comment]
Pipe issue is fixed in 0.1.4.

**Comment by Piasy** [comment]
With `0.1.3.195`, relative path still not work properly, `./gra` still could not be complete to `./gradlew`.

And besides, if I have two dirs, named `Yolo-1` and `YOLO-2` in `~/Desktop`, when I type `cd ~/Desktop/y`, there is no hint, but if I'm in `~/Desktop`, when I type `cd y`, there are hint.

**Comment by shockone** [comment]
@Piasy, should work fine in 0.1.4. Could you confirm, pleae?

**Comment by Piasy** [comment]
With `0.1.4.197`, `./gra` could be completed to `./gradlew`, and `./gradlew tasks | gr` could be completed to `./gradlew tasks | grep` too.

But the problem still exist.

> And besides, if I have two dirs, named `Yolo-1` and `YOLO-2` in `~/Desktop`, when I type `cd ~/Desktop/y`, there is no hint, but if I'm in `~/Desktop`, when I type `cd y`, there are hint.

**Comment by shockone** [comment]
@Piasy, thanks for checking. The YOLO issue was happening because of case sensitivity. Should work in 0.1.5.

**Comment by Piasy** [comment]
Great! Thanks!
